linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - misspell
    - unparam
    - prealloc

linters-settings:
  govet:
    check-shadowing: false
  gofmt:
    simplify: true

run:
  timeout: 5m
