# .goreleaser.yml
version: 2
project_name: gh-rerun-failed

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    main: ./main.go
    binary: gh-rerun-failed

archives:
  - format: tar.gz
    # Standard format gh extension install likes
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
