# .goreleaser.yml
version: 2
project_name: gh-rerun-failed

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    main: ./main.go
    binary: gh-rerun-failed

archives:
  - format: tar.gz
    # exact format gh extension install expects for go extensions
    # we must ensure amd64 is used instead of x86_64
    name_template: "gh-rerun-failed-{{ .Os }}-{{ if or (eq .Arch \"amd64\") (eq .Arch \"x86_64\") }}amd64{{ else }}{{ .Arch }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
