# .goreleaser.yml
version: 2
project_name: gh-rerun-failed

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    main: ./main.go
    binary: gh-rerun-failed

archives:
  - formats: [ tar.gz ]
    # Standard format that gh extension install likes
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [ zip ]

checksum:
  name_template: 'checksums.txt'

snapshots:
  name_template: "next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
